story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('websitegue.urls')),
]

websitegue/urls.py
from django.urls import path

from . import views

app_name = 'websitegue'
urlpatterns = [
    path('', views.index, name="Home"),
    path('profile/',views.profile, name="Profile"),
    path('experiences/',views.experiences, name="Experiences"),
    path('skills/',views.skills, name="Skills"),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/create', views.schedule_create, name='schedule_create'),
    path('schedule/delete', views.schedule_delete, name='schedule_delete'),
]

websitegue/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.activity

websitegue/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

websitegue/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms

# Create your views here.

def index(request):
    return render(request, 'home.html')

def profile(request):
    return render(request, 'profile.html')

def experiences(request):
    return render(request, 'experiences.html')

def skills(request):
    return render(request, 'skills.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('websitegue:schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request):
	Schedule.objects.all().delete()
	return render(request, "schedule.html")

websitegue/templates/experiences.html
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">
        
        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div class="row desc">
            <div class="container-fluid">
                    <div class="col-md-12">
                        <a href="{% url 'websitegue:Home'%}">
                            <img class="home" src="{% static 'image/house.png' %}" title="Home" alt="home">
                        </a>
                        <a href="{% url 'websitegue:Profile'%}" class="btn btn-info" role="button">PROFILE</a>
                        <a href="{% url 'websitegue:Experiences'%}" class="btn btn-info" role="button">EXPERIENCES</a>
                        <a href="{% url 'websitegue:Skills'%}" class="btn btn-info" role="button">SKILLS</a>
                        <a href="{% url 'websitegue:schedule'%}" class="btn btn-info"  role="button">SCHEDULE</a>
                    </div>
                </div>
            <div class="col-md-12">
                <h1>EXPERIENCES</h1>
            </div>
            <div class="col-md-12">
                <pre class="datadiri">

       Kepanitiaan : 

       - Ketua panitia kebaktian gabungan rohani kristen 34 tahun 2017

       - Ketua panitia acara Newbie Cup tahun 2019

       - Staff keamanan High School Celebration tahun 2017

       - Staff keamanan Olim UI tahun 2018

       - Staff TnV Compfest Fasilkom tahun 2019

       - Staff Sponsorship High School Celebration tahun 2016

       - Staff Humas CGT tahun 2018
 
       - PJ kontingen band UIAW
 

       Organisasi :

       - BEM Seni budaya Fasilkom

       - BPH Humas Rohani Kristen 34

       - Gazper XIX

       - Personil band Diverse

       - Personil band Nibels

       - Personil band Glazzy Tunes

       - Personil band Blue Cirrus
                </pre>
            </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

websitegue/templates/home.html
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">

        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div>
            <img class="rounded-circle" alt="avatar" src="{% static 'image/foto.png' %}">
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <p class="nama">JACOB MARULITUA IDO SITUMORANG</p>
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-12">
                    <a href="{% url 'websitegue:Profile'%}" class="btn btn-info" style="margin:10px;" role="button">PROFILE</a>
                    <a href="{% url 'websitegue:Experiences'%}" class="btn btn-info" style="margin:10px;" role="button">EXPERIENCES</a>
                    <a href="{% url 'websitegue:Skills'%}" class="btn btn-info" style="margin:10px;" role="button">SKILLS</a>
                    <a href="{% url 'websitegue:schedule'%}" class="btn btn-info"  role="button">SCHEDULE</a>
                </div>
                <div class="col-md-12">
                        <a href="https://www.instagram.com/jacobstmrg/?hl=en">
                            <img class="social" src="{% static 'image/instagram-logo.png' %}" title="Instagram" alt="ig">
                        </a>
                        <a href="https://twitter.com/SitumorangJacob">
                            <img class="social" src="{% static 'image/twitter.png' %}" title="Twitter" alt="twitter">
                        </a>
                        <a href="https://wa.me/+6281212139002">
                            <img class="social" src="{% static 'image/whatsapp-logo.png' %}" title="WhatsApp" alt="wa">
                        </a>
                        <a href="https://id-id.facebook.com/jacob.zc.9">
                            <img class="social" src="{% static 'image/facebook-logo.png' %}" title="Facebook" alt="facebook">
                        </a>
                </div>  
            </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

websitegue/templates/profile.html
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">
        
        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div class="row desc">
            <div class="container-fluid">
                <div class="col-md-12">
                    <a href="{% url 'websitegue:Home' %}">
                        <img class="home" src="{% static 'image/house.png' %}" title="Home" alt="home">
                    </a>
                    <a href="{% url 'websitegue:Profile' %}" class="btn btn-info"  role="button">PROFILE</a>
                    <a href="{% url 'websitegue:Experiences' %}" class="btn btn-info"  role="button">EXPERIENCES</a>
                    <a href="{% url 'websitegue:Skills'%}" class="btn btn-info"  role="button">SKILLS</a>
                    <a href="{% url 'websitegue:schedule'%}" class="btn btn-info"  role="button">SCHEDULE</a>
                </div>
            </div>
            <div class="col-md-12">
                <h1>PROFILE</h1>
            </div>
            <div class="col-md-7">
                <pre class="datadiri">

       Nama Panggilan    : Jacob 

       Tanggal Lahir        : 8 May 2000

       Pendidikan            : S1 Sistem Informasi - 
                                       Universitas Indonesia

       Agama                  : Kristen Protestan

       Email                   : Jacobzc77@gmail.com

       Jenis Kelamin        : Pria

       NPM                    : 1806185361

       No. telp                : 081212139002

       Status                  : Belum Menikah
                </pre>
            </div>
                <div class="col-md-5">
                    <img class="fotoui" src="{% static 'image/ui.JPG' %}" title="ui" alt="ui">
                </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

websitegue/templates/schedule.html
{% block content %} 
    
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">
        
        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div class="row desc">
            <div class="container-fluid">
                <div class="col-md-12">
                    <a href="{% url 'websitegue:Home'%}">
                        <img class="home" src="{% static 'image/house.png' %}" title="Home" alt="home">
                    </a>
                    <a href="{% url 'websitegue:Profile'%}" class="btn btn-info" role="button">PROFILE</a>
                    <a href="{% url 'websitegue:Experiences'%}" class="btn btn-info" role="button">EXPERIENCES</a>
                    <a href="{% url 'websitegue:Skills'%}" class="btn btn-info" role="button">SKILLS</a>
                    <a href="{% url 'websitegue:schedule'%}" class="btn btn-info"  role="button">SCHEDULE</a>
                </div>
            </div>
        <div class="col-md-12">
            <h1>SCHEDULE</h1>
        </div>
        <div class="container-fluid">
            <a href="{% url 'websitegue:schedule_delete' %}" class="schedulebutton"><button type="button" class="btn btn-primary">CLEAR</button></a>
            <a href="{% url 'websitegue:schedule_create' %}" class="schedulebutton"><button type="button" class="btn btn-primary">CREATE</button></a>
        </div>
        <div class="container kotakschedule">
            <div class="row">
                {% for schedule in schedules %}
                    <div class="col-sm-4 text-center">
                        <P class = "descform">ACTIVITY</p>
                        <p>{{ schedule.activity }}</p>
                        <P class = "descform">DATE</p>
                        <p>{{ schedule.date.date }}</p>
                        <P class = "descform">TIME</p>
                        <p>{{ schedule.time}}</p>
                        <P class = "descform">PLACE</p>
                        <p>{{ schedule.place }}</p>
                        <P class = "descform">CATEGORY</p>
                        <p>{{ schedule.category }}</p>
                        <hr class="linesched">
                    </div>
                {% endfor %}
            </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>
{% endblock %}

websitegue/templates/schedule_create.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">
        
        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div class="row desc">
            <div class="container-fluid">
                <div class="col-md-12">
                    <a href="{% url 'websitegue:Home'%}">
                        <img class="home" src="{% static 'image/house.png' %}" title="Home" alt="home">
                    </a>
                    <a href="{% url 'websitegue:Profile'%}" class="btn btn-info" role="button">PROFILE</a>
                    <a href="{% url 'websitegue:Experiences'%}" class="btn btn-info" role="button">EXPERIENCES</a>
                    <a href="{% url 'websitegue:Skills'%}" class="btn btn-info" role="button">SKILLS</a>
                    <a href="{% url 'websitegue:schedule'%}" class="btn btn-info"  role="button">SCHEDULE</a>
                </div>
            </div>
        <div class="col-md-12">
            <h1>SCHEDULE</h1>
        </div>
        <form class="forms" action="{% url 'websitegue:schedule_create' %}" method="post">
            <div class="container-fluid">
                <a href="{% url 'websitegue:schedule_delete' %}" class="schedulebutton"><button type="submit" class="btn btn-primary" value="Add">ADD</button></a>
            </div>
            <div class="container kotakschedule">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-sm-10">
                        {% for fields in form %}
                            {{ fields.label_tag }}
                            <br>
                            {{ fields }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

websitegue/templates/skills.html
<!doctype html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

        <link rel="icon" href="{% static 'image/saxophone.png' %}">
        
        <title>Website Gue</title>
    </head>
    <body class="bg">
        <div class="row desc">
            <div class="container-fluid">
                <div class="col-md-12">
                    <a href="{% url 'websitegue:Home'%}">
                        <img class="home" src="{% static 'image/house.png' %}" title="Home" alt="home">
                    </a>
                    <a href="{% url 'websitegue:Profile'%}" class="btn btn-info" role="button">PROFILE</a>
                    <a href="{% url 'websitegue:Experiences'%}" class="btn btn-info" role="button">EXPERIENCES</a>
                    <a href="{% url 'websitegue:Skills'%}" class="btn btn-info" role="button">SKILLS</a>
                    <a href="{% url 'websitegue:schedule'%}" class="btn btn-info"  role="button">SCHEDULE</a>
                </div>
            </div>
        <div class="col-md-12">
            <h1>SKILLS</h1>
        </div>
        <div class="container skillbar">
            <div class="bar front expert" data-skill="MUSIC"></div>
            <div class="bar back basic" data-skill="PROGRAMMING"></div>
            <div class="bar front advanced" data-skill="SOCIAL"></div>
            <div class="bar back intermediate" data-skill="LEADERSHIP"></div>
            <div class="bar front advanced" data-skill="TEAMWORK"></div>
            <div class="bar back basic" data-skill="MARKETING"></div>
            <div class="bar back intermediate" data-skill="PROBLEM_SOLVING"></div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>